kind: pipeline
name: CaptureTheBlock-Master
type: docker

steps:
  - name: test'n'deploy
    image: maven:3.8.5-eclipse-temurin-16
    environment:
      NRM_PW:
        from_secret: NEXUS_DEV_PWD
    commands:
      - mvn install -DskipTests=true -B -V -s workflow_settings.xml
      - mvn test -B -s workflow_settings.xml
      - mvn deploy -B -s workflow_settings.xml

trigger:
  event:
    - push
